### ISSUE TITLE
Mail default design (header/footer)

### ISSUE THREAD

**Issue by marceloboeira** [freaktags/core#119]
The idea is to create a default header and footer for mails, that will be used for every mail. 
About logo and colors, can be based on the default info:

https://github.com/freaktags/design/blob/master/logo/sources/manual_de_identidade_visual_FreakTags.pdf?raw=true

**Comment by rmoraes** [comment]
template source:
http://themeforest.net/item/simpleapp-email-notification-templates/full_screen_preview/9608791

**Comment by marceloboeira** [comment]
@rmoraes that's just amazing, thanks a lot!
