### ISSUE TITLE
Layout HTML/JS

### ISSUE THREAD

**Issue by marvin52** [freaktags/core#41]
Develop the first front-end template for the app

**Comment by marceloboeira** [comment]
@marvin52 I'm going to create labels to front-end stuff. Like: design, layout and front-end.

* Design: specific to changes on all system, design issues.
* Front-end: HTML/JS Front-end problems or new features, like some animations and development matters.

Do you need other labels?

**Comment by marvin52** [comment]
Thats enough @marceloboeira

**Comment by marceloboeira** [comment]
@marvin52 alright! It's already on the roadmap, when you feel ready change it on the board, remember to put any commit on a another branch. And as you are a team member, don't need to fork, just clone and pull request every new feature because I need to review :+1:
